from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

import faiss
import torch


ROOT = Path(__file__).resolve().parents[1]
MODEL_ROOT = ROOT / "models" / "voices" / "raw"
SOURCE_AUDIO = ROOT / ".tools" / "voice-work" / "little-prince-chapter-1-source.mp3"
OUTPUT_DIR = ROOT / "assets" / "audio" / "narration" / "little-prince"
MANIFEST_PATH = ROOT / "assets" / "audio" / "narration" / "voice_manifest.json"
DART_MANIFEST_PATH = ROOT / "lib" / "src" / "generated" / "voice_manifest.g.dart"

VOICES = {
    "narrator": {"name": "Narrator", "pitch": 0, "old": "chapter-1-daily-dose.wav"},
    "heroine": {"name": "Young Heroine", "pitch": 12, "old": "chapter-1-heroine.wav"},
    "hero": {"name": "Young Hero", "pitch": 0, "old": "chapter-1-hero.wav"},
    "deep": {"name": "Deep Character", "pitch": 0, "old": "chapter-1-deep.wav"},
    "elder": {"name": "Elder / Extra", "pitch": 0, "old": "chapter-1-elder.wav"},
}


def file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for block in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def find_pair(folder: Path) -> tuple[Path, Path]:
    models = list(folder.glob("*.pth"))
    indexes = list(folder.glob("*.index")) + list(folder.glob("*.model"))
    if len(models) != 1 or len(indexes) != 1:
        raise ValueError("needs exactly one .pth and one .index or .model file")
    return models[0], indexes[0]


def validate_pair(model: Path, index: Path) -> str:
    checkpoint = torch.load(model, map_location="cpu", weights_only=True)
    version = str(checkpoint.get("version", "v2"))
    faiss.read_index(str(index))
    return version if version in {"v1", "v2"} else "v2"


def convert(model: Path, index: Path, output: Path, version: str, pitch: int) -> None:
    command = [
        sys.executable,
        "-m",
        "rvc_python",
        "cli",
        "-i",
        str(SOURCE_AUDIO),
        "-o",
        str(output),
        "-mp",
        str(model),
        "-ip",
        str(index),
        "-de",
        "cuda:0",
        "-me",
        "rmvpe",
        "-v",
        version,
        "-ir",
        "0.75",
        "-rmr",
        "0.25",
        "-pr",
        "0.33",
        "-pi",
        str(pitch),
    ]
    subprocess.run(command, cwd=ROOT, check=True)


def write_dart_manifest(manifest: dict) -> None:
    lines = [
        "// Generated by tool/sync_voice_audio.py. Do not edit by hand.",
        "const generatedVoiceModels = <String, String>{",
    ]
    for voice_id, voice in manifest["voices"].items():
        if voice.get("available"):
            lines.append(f'  "{voice_id}": {json.dumps(voice["model"])},')
    lines.extend(["};", "", "const generatedVoiceAudio = <String, Map<String, String>>{"])
    for chapter_id, paths in manifest["chapters"].items():
        lines.append(f'  "{chapter_id}": <String, String>{{')
        for voice_id, path in paths.items():
            lines.append(f'    "{voice_id}": {json.dumps(path)},')
        lines.append("  },")
    lines.extend(["};", ""])
    DART_MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    DART_MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not SOURCE_AUDIO.exists():
        print(f"Missing source narration: {SOURCE_AUDIO}")
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    source_fingerprint = file_hash(SOURCE_AUDIO)
    manifest = {
        "voices": {},
        "chapters": {"little-prince-chapter-1": {}},
    }
    failed = False

    for voice_id, settings in VOICES.items():
        folder = MODEL_ROOT / voice_id
        try:
            model, index = find_pair(folder)
            version = validate_pair(model, index)
            model_fingerprint = hashlib.sha256(
                f"{file_hash(model)}:{file_hash(index)}".encode()
            ).hexdigest()
            audio_fingerprint = hashlib.sha256(
                f"{model_fingerprint}:{source_fingerprint}:{settings['pitch']}".encode()
            ).hexdigest()[:10]
            output = OUTPUT_DIR / f"chapter-1-{voice_id}-{audio_fingerprint}.wav"

            if output.exists():
                print(f"{voice_id}: unchanged")
            else:
                print(f"{voice_id}: generating with {model.name}")
                convert(model, index, output, version, settings["pitch"])

            for old_output in OUTPUT_DIR.glob(f"chapter-1-{voice_id}-*.wav"):
                if old_output != output:
                    old_output.unlink()
            legacy_output = OUTPUT_DIR / settings["old"]
            if legacy_output != output and legacy_output.exists():
                legacy_output.unlink()

            manifest["voices"][voice_id] = {
                "available": True,
                "model": model.name,
                "index": index.name,
                "fingerprint": model_fingerprint[:12],
            }
            manifest["chapters"]["little-prince-chapter-1"][voice_id] = (
                f"audio/narration/little-prince/{output.name}"
            )
        except Exception as error:
            failed = True
            print(f"{voice_id}: unavailable ({error})")
            manifest["voices"][voice_id] = {
                "available": False,
                "error": str(error),
            }

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    write_dart_manifest(manifest)
    print(f"Manifest: {MANIFEST_PATH}")
    print(f"Flutter manifest: {DART_MANIFEST_PATH}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
